name: Discord Notification on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue is created by me
        if: github.event.issue.user.login == 'SwetanshuSingh'
        run: echo "Issue created by me, proceeding to send notification to Discord."

      - name: Send message to Discord
        if: github.event.issue.user.login == 'SwetanshuSingh'
        run: |
          issue_number=$(jq '.issue.number' $GITHUB_EVENT_PATH)
          issue_title=$(jq -r '.issue.title' $GITHUB_EVENT_PATH)
          issue_url=$(jq -r '.issue.html_url' $GITHUB_EVENT_PATH)
          issue_body=$(jq -r '.issue.body' $GITHUB_EVENT_PATH)
          author=$(jq -r '.issue.user.login' $GITHUB_EVENT_PATH)

          # Send the Discord notification with issue details
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"An issue has been created by $author.\\n**Issue #$issue_number**: $issue_title\\n**URL**: $issue_url\\n**Description**: $issue_body\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
